=== Demven/issuetracker_dzmitry_salnikau/src/main/resources/xml/builds.xsd
<?xml version="1.0" encoding="UTF-8"?>
<schema  xmlns="http://www.w3.org/2001/XMLSchema" 
  targetNamespace="http://www.issuetracker.training.org/builds" 
  xmlns:tns="http://www.issuetracker.training.org/builds">
	<element name = "builds">
		<complexType>
			<sequence>
				<element name="build" type="tns:build" minOccurs="0" maxOccurs="unbounded" />
			</sequence>
		</complexType>
	</element> 
	
	<complexType name="build">
		<sequence>
			<element name="project" type="string" />
			<element name="version" type="string" />
		</sequence>
		<attribute name="id" type="integer" use="required" />
	</complexType>
    
</schema>

=== Demven/issuetracker_dzmitry_salnikau/src/main/resources/xml/builds.xml
<?xml version="1.0" encoding="UTF-8"?>
<tns:builds xmlns:tns="http://www.issuetracker.training.org/builds" 
  xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"  
  xsi:schemaLocation="http://www.issuetracker.training.org/builds builds.xsd">
	<build id = "1">
		<project>1</project>
		<version>0.6</version>
	</build>
	<build id = "2">
		<project>2</project>
		<version>0.4</version>
	</build>
	<build id = "3">
		<project>3</project>
		<version>1.0</version>
	</build>
	<build id = "4">
		<project>4</project>
		<version>0.8</version>
	</build>
	<build id = "5">
		<project>5</project>
		<version>0.2</version>
	</build>
</tns:builds>
