=== Demven/issuetracker_dzmitry_salnikau/src/main/resources/xml/projects.xsd
<?xml version="1.0" encoding="UTF-8"?>
<schema  xmlns="http://www.w3.org/2001/XMLSchema" 
  targetNamespace="http://www.issuetracker.training.org/projects" 
  xmlns:tns="http://www.issuetracker.training.org/projects">
	<element name = "projects">
		<complexType>
			<sequence>
				<element name="project" type="tns:project" minOccurs="0" maxOccurs="unbounded" />
			</sequence>
		</complexType>
	</element> 
	
	<complexType name="project">
		<sequence>
			<element name="name" type="string" />
			<element name="description" type="string" />
			<element name="manager" type="string" />
		</sequence>
		<attribute name="id" type="integer" use="required" />
	</complexType>
    
</schema>

=== Demven/issuetracker_dzmitry_salnikau/src/main/resources/xml/projects.xml
<?xml version="1.0" encoding="UTF-8"?>
<tns:projects xmlns:tns="http://www.issuetracker.training.org/projects" 
  xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"  
  xsi:schemaLocation="http://www.issuetracker.training.org/projects projects.xsd">
	<project id = "1">
		<name>IMAGEnarium</name>
		<description>Web-application for upload and processing photos in a great variety of ways.</description>
		<manager>3</manager>
	</project>
	<project id = "2">
		<name>MTBank Linux-client</name>
		<description>Java application for Linux to interact with MTBank server</description>
		<manager>4</manager>
	</project>
	<project id = "3">
		<name>Drive2 for Android</name>
		<description>Android client for Drive2.ru</description>
		<manager>5</manager>
	</project>
	<project id = "4">
		<name>BugTracker</name>
		<description>Web-application for our company for tracking bugs in our projects.</description>
		<manager>1</manager>
	</project>
	<project id = "5">
		<name>EYEkey</name>
		<description>Application for using eye-movements for typing without keyboard or mouse.</description>
		<manager>8</manager>
	</project>
</tns:projects>
